### ISSUE TITLE
Convert CloudFormation and Terraform

### ISSUE THREAD

**Issue by PatMyron** [PatMyron/terraformation#4]
literal resource properties / arguments before other sections:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
https://terraform.io/language/

https://github.com/hashicorp/terraform-provider-awscc/issues/118

~80% CloudFormation resource types now supported by **[`awscc`](https://github.com/hashicorp/terraform-provider-awscc/)**

---

```hcl
variable "in" {
} # https://terraform.io/language/values/variables
resource "awscc_logs_log_group" "resource" {
  retention_in_days = 1
}
output "out" {
  value = "out"
} # https://terraform.io/language/values/outputs
```

```yaml
Parameters:
  In: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
    Type: String
Resources:
  Resource:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
Outputs:
  Out: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
    Value: out
```
